---
- hosts: all
  become: true
  become_method: sudo
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - nginx
    - mariadb
    - mongodb
    - php
    - xdebug
    - composer